# Generated by Django 5.0.6 on 2024-07-03 15:57

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_phone', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/logo/', verbose_name='عکس پروفایل کاربری')),
                ('gender_class', models.CharField(choices=[('M', 'آقا'), ('F', 'خانم'), ('O', 'دیگر')], max_length=10, verbose_name='جنسیت')),
                ('military_class', models.CharField(choices=[('EP', 'معافیت تحصیلی'), ('SE', 'معافیت خاص'), ('ME', 'معافیت پزشکی'), ('TEOS', 'پایان خدمت'), ('I', 'مشمول'), ('NI', 'شامل من نمیشه')], max_length=10, verbose_name='وضعیت خدمت')),
                ('marital_class', models.CharField(choices=[('MARRIED', 'متاهل'), ('SINGLE', 'مجرد'), ('DIVORCED', 'مطلقه')], max_length=10, verbose_name='وضعیت ازدواج')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 7, 3), verbose_name='تاریخ ثبت نام')),
                ('birth_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('country', models.CharField(blank=True, max_length=5000, null=True, verbose_name='کشور')),
                ('city', models.CharField(max_length=5000, verbose_name='شهر')),
                ('state', models.CharField(max_length=5000, verbose_name='استان')),
                ('job', models.CharField(max_length=100, verbose_name='شغل')),
                ('requested_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='حقوق درخواستی')),
                ('show_salary', models.BooleanField(default=False, verbose_name='نمایش حقوق در رزومه')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن')),
                ('active_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت کاربر')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='متن درباره من')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درباره کاربر',
                'verbose_name_plural': 'درباره کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1000, verbose_name='مقطع تحصیلی')),
                ('field_of_study', models.CharField(max_length=1000, verbose_name='رشته تحصیلی')),
                ('university_name', models.CharField(max_length=1000, verbose_name='نام دانشگاه')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ فارغ التحصیل')),
                ('studying', models.BooleanField(default=False, verbose_name='در حال تحصیل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحصیل کاربر',
                'verbose_name_plural': 'تحصیلات کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='عنوان زبان')),
                ('Language_rank', models.IntegerField(help_text='این فیلد بین 1 تا 5 پر میشود', verbose_name='درجه تسلط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مهارت زبان',
                'verbose_name_plural': 'مهارت های زبان',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_name', models.CharField(max_length=500, verbose_name='نام توصیه کننده')),
                ('relationship_with_recommender', models.CharField(max_length=500, verbose_name='نوع رابطه با توصیه کننده')),
                ('recommender_email', models.EmailField(max_length=500, verbose_name='ایمیل توصیه کننده')),
                ('recommender_phone', models.EmailField(max_length=15, verbose_name='تلفن توصیه کننده')),
                ('request_text', models.TextField(verbose_name='متن درخواست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توصیه نامه',
                'verbose_name_plural': 'توصیه نامه ها',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=500, verbose_name='عنوان مهارت')),
                ('skill_type', models.CharField(choices=[('H', 'سخت'), ('S', 'نرم')], max_length=1, verbose_name='نوع مهارت')),
                ('skill_rank', models.IntegerField(help_text='این فیلد بین 1 تا 5 پر میشود', verbose_name='درجه تسلط')),
                ('skill_logo', models.ImageField(blank=True, null=True, upload_to='users/skill/', verbose_name='لگو مهارت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مهارت کاربر',
                'verbose_name_plural': 'مهارت کاربرالن',
            },
        ),
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_title', models.CharField(max_length=5000, verbose_name='آدرس')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('logo', models.ImageField(upload_to='users/social/', verbose_name='لگو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی کاربر',
                'verbose_name_plural': 'شبکه اجتماعی کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500, verbose_name='عنوان شغل')),
                ('company_name', models.CharField(max_length=500, verbose_name='نام شرکت')),
                ('industry', models.CharField(max_length=500, verbose_name='صنعت')),
                ('side', models.CharField(max_length=500, verbose_name='سمت')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ترک شغل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'سابقه شغل',
                'verbose_name_plural': 'سوابق شغلی',
            },
        ),
        migrations.CreateModel(
            name='UserWorkSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_sample_title', models.CharField(max_length=500, verbose_name='عنوان نمونه کار')),
                ('work_sample_description', models.TextField(verbose_name='توضیحات')),
                ('work_sample_image', models.ImageField(blank=True, null=True, upload_to='users/work/', verbose_name='تصویر نمونه کار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_work_samples', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
