# Generated by Django 5.0.6 on 2024-07-03 16:02

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_class',
            field=models.CharField(blank=True, choices=[('M', 'آقا'), ('F', 'خانم'), ('O', 'دیگر')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_class',
            field=models.CharField(blank=True, choices=[('MARRIED', 'متاهل'), ('SINGLE', 'مجرد'), ('DIVORCED', 'مطلقه')], max_length=10, null=True, verbose_name='وضعیت ازدواج'),
        ),
        migrations.AlterField(
            model_name='user',
            name='military_class',
            field=models.CharField(blank=True, choices=[('EP', 'معافیت تحصیلی'), ('SE', 'معافیت خاص'), ('ME', 'معافیت پزشکی'), ('TEOS', 'پایان خدمت'), ('I', 'مشمول'), ('NI', 'شامل من نمیشه')], max_length=10, null=True, verbose_name='وضعیت خدمت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_salary',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='نمایش حقوق در رزومه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='استان'),
        ),
    ]
