# Generated by Django 5.0.6 on 2024-07-04 07:45

import ckeditor.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birth_date_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': 'مهارت کاربر', 'verbose_name_plural': 'مهارت کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 7, 4), verbose_name='تاریخ ثبت نام'),
        ),
        migrations.AlterField(
            model_name='userabout',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='متن درباره من'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommender_phone',
            field=models.CharField(max_length=15, verbose_name='تلفن توصیه کننده'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='request_text',
            field=ckeditor.fields.RichTextField(verbose_name='متن درخواست'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='social_title',
            field=models.CharField(max_length=5000, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='userworksamples',
            name='work_sample_description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
    ]
