# Generated by Django 5.0.6 on 2024-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userskill_options_alter_user_register_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguage',
            name='Language_rank',
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='comprehension_rank',
            field=models.IntegerField(default=1, help_text='این فیلد بین 1 تا 5 پر میشود', verbose_name='درجه درک مطلب'),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='read_rank',
            field=models.IntegerField(default=1, help_text='این فیلد بین 1 تا 5 پر میشود', verbose_name='درجه تسلط خواندن'),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='write_rank',
            field=models.IntegerField(default=1, help_text='این فیلد بین 1 تا 5 پر میشود', verbose_name='درجه تسلط نوشتن'),
        ),
    ]
