# Generated by Django 5.0.6 on 2024-07-04 08:37

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userlanguage_language_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='نام . نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن همراه')),
                ('request_text', models.TextField(verbose_name='متن درخواست')),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2024, 7, 4), verbose_name='تاریخ درخواست')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام همکار')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, help_text='این فیلد اختیاری می باشد.', null=True, upload_to='user/partners/', verbose_name='لگو')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکاران',
            },
        ),
    ]
