# Generated by Django 5.0.6 on 2024-07-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactus_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='این فیلد اختیاری می باشد.', null=True, upload_to='users/partners/', verbose_name='لگو'),
        ),
    ]
