# Generated by Django 5.0.6 on 2024-07-04 08:49

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی مقالات',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='عنوان')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
                ('created_at', django_jalali.db.models.jDateField(default=datetime.date(2024, 7, 4), verbose_name='تاریخ ساخت مقاله')),
                ('pub_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=False, verbose_name='وضعیت انتشار (یافت/نیافت)')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت(فعال/غیرفعال)')),
                ('cover_image', models.ImageField(upload_to='blog/cover', verbose_name='تصویر اصلی')),
                ('alt_attr', models.CharField(max_length=1000, verbose_name='متن جایگزین کاور')),
                ('title_attr', models.CharField(max_length=1000, verbose_name='عنوان کاور')),
                ('view_count', models.IntegerField(default=1, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_user', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='blog.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('name', 'name'), ('property', 'property')], max_length=1000, verbose_name='نوع')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_seo', to='blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'سئو مقاله',
                'verbose_name_plural': 'سئو مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تگ مقاله',
                'verbose_name_plural': 'تگ مقالات',
            },
        ),
    ]
