# Generated by Django 5.0.6 on 2024-07-04 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_type', models.CharField(max_length=500, verbose_name='نوع پلن')),
                ('planing_price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('planing_name', models.CharField(max_length=500, verbose_name='نام پلن')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='users/plans/', verbose_name='تصویر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planing', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پلن فروش',
                'verbose_name_plural': 'پلن های فروش',
            },
        ),
        migrations.CreateModel(
            name='PlaningFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=500, verbose_name='نام مشخصه')),
                ('feature_value', models.CharField(max_length=500, verbose_name='مقدار مشخصه')),
                ('planing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planing_feature', to='planing.planing', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'ویژگی پلن',
                'verbose_name_plural': 'ویژگی های پلن',
            },
        ),
    ]
