# Generated by Django 5.0.6 on 2024-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='validity',
            field=models.CharField(blank=True, help_text='مانند : هفته ای، ماهانه ، سالانه و...', max_length=500, null=True, verbose_name='مدت اعتبار'),
        ),
    ]
